const assert = require('node:assert/strict')
const path = require('node:path')
const fs = require('node:fs')
const { chromium } = require('playwright')

async function main() {
  const url = process.argv[2]
  if (!url) throw new Error('Usage: node scripts/history-smoke.cjs URL (use an isolated fixture server)')
  const output = path.resolve('.tmp-history-browser')
  fs.mkdirSync(output, { recursive: true })
  const browser = await chromium.launch({ headless: true, executablePath: process.env.PLAYWRIGHT_CHROME_PATH || (process.platform === 'win32' ? 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe' : undefined) })
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  try {
    await page.goto(url)
    await page.getByRole('button', { name: 'Saved plans', exact: true }).click()
    await page.getByText('No saved plans yet').waitFor()
    await page.getByRole('button', { name: 'Close', exact: true }).click()
    await page.getByRole('button', { name: 'Mark reviewed — keep all', exact: true }).click()
    await page.getByRole('button', { name: 'Save plan', exact: true }).click()
    await page.getByLabel('Plan name', { exact: true }).fill('First review')
    await page.getByRole('button', { name: 'Save plan safely' }).click()
    await page.getByRole('dialog').waitFor({ state: 'hidden' })
    await page.getByRole('button', { name: 'Saved plans', exact: true }).click()
    await page.getByRole('button', { name: 'Rename First review', exact: true }).click()
    await page.getByLabel('New plan name').fill('保留 final review')
    await page.getByRole('button', { name: 'Save name', exact: true }).click()
    await page.getByRole('heading', { name: '保留 final review', exact: true }).waitFor()
    await page.getByText(/1 reviewed sets/).waitFor()
    await page.screenshot({ path: path.join(output, 'plans-desktop.png') })
    await page.setViewportSize({ width: 390, height: 844 })
    const dialog = page.getByRole('dialog', { name: 'Saved plans' })
    assert.equal(await dialog.evaluate((element) => element.scrollWidth <= element.clientWidth), true)
    await page.screenshot({ path: path.join(output, 'plans-mobile.png') })
    await page.getByRole('button', { name: 'Load 保留 final review', exact: true }).click()
    await dialog.waitFor({ state: 'hidden' })
    await page.reload()
    const session = await page.evaluate(async () => (await fetch('/api/session')).json())
    assert.equal(session.initialDecisions.length, 1)
    await page.getByRole('button', { name: 'Saved plans', exact: true }).click()
    await page.getByRole('heading', { name: '保留 final review', exact: true }).waitFor()
    assert.deepEqual(errors, [])
    await page.getByRole('button', { name: 'Close', exact: true }).click()
    await page.getByRole('button', { name: 'Mark reviewed — keep all', exact: true }).click()
    await page.getByRole('button', { name: 'Saved plans', exact: true }).click()
    assert.equal(await page.getByRole('button', { name: 'Load 保留 final review', exact: true }).isDisabled(), true)
    await page.getByText('Save your current decisions before loading another plan.').waitFor()
    console.log('PASS: save decisions, rename, load, reload, unsaved-change guard, desktop/mobile layout; no page errors')
  } finally {
    await browser.close()
  }
}
main().catch((error) => { console.error(error); process.exitCode = 1 })
